import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const SUPABASE_URL = "https://supabase.samecdigital.com";
const SUPABASE_ANON_KEY =
  "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc4MDY5NTYwMCwiZXhwIjo0OTM2MzY5MjAwLCJyb2xlIjoiYW5vbiJ9.OIvu-YM9AzPKdCngJ2tHPl2emYP8OFxvYhTtAAErnKk";
const SITE_ID = "63253275-f6ac-4c50-8755-c8d385b758ff";

type Redirect = {
  from_url: string;
  to_url: string;
  code: 301 | 302;
  source: string;
};

function toRelative(url: string): string {
  if (url.startsWith("http://") || url.startsWith("https://")) {
    try {
      const u = new URL(url);
      return u.pathname + u.search + u.hash;
    } catch {
      return url;
    }
  }
  return url.startsWith("/") ? url : `/${url}`;
}

function escapeApache(s: string): string {
  return s.replace(/([.+?^${}()|[\]\\])/g, "\\$1");
}

/**
 * Phase 0 audit produced redirect targets assuming flat /{slug}/ URLs,
 * but the Astro build uses /kategorie/{slug}/. This normalizes the target
 * paths to match actual deployed routes — without modifying the source DB.
 *
 * Also fixes the `automoto` → `auto-moto` slug spelling.
 */
const CATEGORY_SLUGS = new Set([
  "tech",
  "auto-moto",
  "lifestyle",
  "zabava",
  "cestovani",
  "finance",
]);
const SLUG_ALIAS: Record<string, string> = {
  automoto: "auto-moto",
};
function normalizeTarget(path: string): string {
  // Pagination archives → homepage (no equivalent in new site)
  if (/^\/page(\/|$)/.test(path)) return "/";

  // Match a single-segment slug like /zabava/ or /automoto/
  const m = path.match(/^\/([a-z][a-z0-9-]*)\/?$/);
  if (!m) return path;
  const raw = m[1];
  const canonical = SLUG_ALIAS[raw] ?? raw;
  if (CATEGORY_SLUGS.has(canonical)) {
    return `/kategorie/${canonical}/`;
  }
  return path;
}

/**
 * Snapshot posledních úspěšně stažených redirectů. Je VERZOVANÝ schválně:
 * `public/.htaccess` je v .gitignore, takže na čistém CI runneru není z čeho
 * stavět, když Supabase nedojede — a build bez těch 141 migračních 301
 * by web tiše připravil o přesměrování z WordPressu.
 */
const SNAPSHOT = join(process.cwd(), "scripts", "redirects-snapshot.json");

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * Supabase běží na vlastním VPS a z GitHub runnerů občas vytimeoutuje
 * (UND_ERR_CONNECT_TIMEOUT po 10 s) — 31. 8. 2026 to shodilo deploy dvakrát,
 * přičemž z lokálu odpovídá za 0,14 s. Proto tři pokusy s delším limitem,
 * a teprve pak snapshot.
 */
async function fetchRedirects(): Promise<{ rows: Redirect[]; stale: boolean }> {
  const url =
    `${SUPABASE_URL}/rest/v1/redirects` +
    `?site_id=eq.${SITE_ID}&select=from_url,to_url,code,source`;

  let lastErr: unknown;
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const res = await fetch(url, {
        headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}` },
        signal: AbortSignal.timeout(30_000),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status} ${await res.text()}`);
      const rows = (await res.json()) as Redirect[];
      if (!Array.isArray(rows)) throw new Error("nečekaný tvar odpovědi");
      if (rows.length === 0) throw new Error("0 redirectů — beru jako chybu, ne jako prázdnou tabulku");
      return { rows, stale: false };
    } catch (err) {
      lastErr = err;
      console.warn(`⚠ pokus ${attempt}/3 o načtení redirectů selhal: ${String(err)}`);
      if (attempt < 3) await sleep(attempt * 3000);
    }
  }

  if (existsSync(SNAPSHOT)) {
    const rows = JSON.parse(readFileSync(SNAPSHOT, "utf8")) as Redirect[];
    console.warn(
      `⚠ Supabase nedostupná → beru snapshot (${rows.length} redirectů). ` +
        `Web se postaví, ale redirecty můžou být zastaralé.`
    );
    return { rows, stale: true };
  }

  console.error(
    "✗ Supabase nedostupná a snapshot neexistuje — build zastavuju schválně.\n" +
      "  Postavit web bez migračních 301 by tiše zabilo přesměrování z WordPressu."
  );
  throw lastErr;
}

async function main() {
  const { rows, stale } = await fetchRedirects();

  // Snapshot obnovuju jen z čerstvých dat, ať ho nepřepíšu sám sebou.
  if (!stale) {
    mkdirSync(join(process.cwd(), "scripts"), { recursive: true });
    writeFileSync(SNAPSHOT, JSON.stringify(rows, null, 2) + "\n", "utf8");
  }

  const lines: string[] = [];
  lines.push("# Generated by scripts/generate-htaccess.ts — DO NOT EDIT.");
  lines.push(`# Source: Supabase redirects table (site_id=${SITE_ID})`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("Options -Indexes");
  lines.push("");
  lines.push("# Staging subdomain: prevent search engine indexing of duplicate content");
  lines.push("# Production (aktualizovano.cz) — no header, indexes normally");
  lines.push("<IfModule mod_setenvif.c>");
  lines.push("  SetEnvIfNoCase Host \"^staging\\.\" AKT_STAGING=1");
  lines.push("</IfModule>");
  lines.push("<IfModule mod_headers.c>");
  lines.push("  Header set X-Robots-Tag \"noindex, nofollow, nosnippet\" env=AKT_STAGING");
  lines.push("</IfModule>");
  lines.push("");
  lines.push("<IfModule mod_rewrite.c>");
  lines.push("RewriteEngine On");
  lines.push("");
  lines.push("# Affiliate wildcard 301 → homepage (preserves Wikipedia DR 97 links + others)");
  lines.push("# Phase 0 emergency fix; replace with per-hash Cloudflare rules in Phase 4+");
  lines.push("RewriteRule ^l-sk/c-.*$ / [R=301,L]");
  lines.push("RewriteRule ^l-cs/c-.*$ / [R=301,L]");
  lines.push("RewriteRule ^l-sk/source-.*$ / [R=301,L]");
  lines.push("");
  lines.push("# Baseline category redirects — every /category/{slug}/ → /kategorie/{slug}/");
  lines.push("# (covers slugs not in Phase 0 audit, e.g. lifestyle added post-audit)");
  for (const slug of [...CATEGORY_SLUGS].sort()) {
    lines.push(`RewriteRule ^category/${slug}/?$ /kategorie/${slug}/ [R=301,L]`);
  }
  lines.push("");
  lines.push(`# ${rows.length} explicit redirects from Supabase`);

  const stripTrailing = (s: string) => s.replace(/\/+$/, "");
  const normalize = (s: string) => stripTrailing(s).toLowerCase();

  const seen = new Set<string>();
  let written = 0;
  let skipped = 0;
  for (const r of rows) {
    const from = toRelative(r.from_url);
    const to = normalizeTarget(toRelative(r.to_url));
    if (normalize(from) === normalize(to)) {
      skipped++;
      continue;
    }
    const fromKey = normalize(from);
    if (seen.has(fromKey)) {
      skipped++;
      continue;
    }
    seen.add(fromKey);

    const fromPattern = stripTrailing(from).replace(/^\//, "");
    const pattern = `^${escapeApache(fromPattern)}/?$`;
    const flags = `R=${r.code},L`;
    lines.push(`RewriteRule ${pattern} ${to} [${flags}]  # ${r.source}`);
    written++;
  }
  lines.push("");
  lines.push("# Removed pagination — stránkování zrušeno, /{slug}/{n}/ → /{slug}/");
  lines.push("RewriteRule ^kategorie/([^/]+)/[0-9]+/?$ /kategorie/$1/ [R=301,L]");
  lines.push("RewriteCond %{REQUEST_FILENAME} !-f");
  lines.push("RewriteCond %{REQUEST_FILENAME} !-d");
  lines.push("RewriteRule ^([^/]+)/[0-9]+/?$ /$1/ [R=301,L]");
  lines.push("");
  lines.push("# WP legacy URL fallbacks — handle long tail of pre-migration URLs");
  lines.push("# RSS feeds (any /feed/ or /*/feed/ path)");
  lines.push("RewriteRule ^feed/?$ /rss.xml [R=301,L]");
  lines.push("RewriteRule ^.+/feed/?$ /rss.xml [R=301,L]");
  lines.push("# WP search ?s=X → Pagefind /hledat?q=X");
  lines.push("RewriteCond %{QUERY_STRING} ^s=(.+)$");
  lines.push("RewriteRule ^$ /hledat?q=%1 [R=301,L]");
  lines.push("# Tag / author archives — not migrated. 410 Gone (ne 301→homepage:");
  lines.push("# redirect-na-homepage Google hodnotí jako soft 404 a drží v reportu");
  lines.push("# \"neindexováno\"; 410 je trvale zahodí a report se zmenší).");
  lines.push("RewriteRule ^tag/.*$ - [G,L]");
  lines.push("RewriteRule ^author/.*$ - [G,L]");
  lines.push("# wp-admin probes (bots) — silently route to homepage");
  lines.push("RewriteRule ^wp-admin/?.*$ / [R=301,L]");
  lines.push("RewriteRule ^wp-login\\.php$ / [R=301,L]");
  lines.push("");
  lines.push("# Clean URL fallback — Astro static directory index");
  lines.push("DirectoryIndex index.html");
  lines.push("");
  lines.push("# Custom 404");
  lines.push("ErrorDocument 404 /404.html");
  lines.push("</IfModule>");
  lines.push("");

  // Static asset caching + compression. Self-hosted fonty mají stabilní jména →
  // 1 rok immutable. Ostatní assety (css/js/img) 30 dní s revalidací (pagefind
  // soubory mají stabilní cesty, proto NE immutable). HTML krátce (denní rebuild).
  // Řeší Lighthouse cache-insight.
  lines.push("# === Static asset caching ===");
  lines.push("<IfModule mod_headers.c>");
  lines.push('  <FilesMatch "\\.(woff2|woff|ttf|otf)$">');
  lines.push('    Header set Cache-Control "public, max-age=31536000, immutable"');
  lines.push("  </FilesMatch>");
  lines.push('  <FilesMatch "\\.(css|js|svg|jpg|jpeg|png|webp|avif|gif|ico)$">');
  lines.push('    Header set Cache-Control "public, max-age=2592000"');
  lines.push("  </FilesMatch>");
  lines.push('  <FilesMatch "\\.html$">');
  lines.push('    Header set Cache-Control "public, max-age=600, must-revalidate"');
  lines.push("  </FilesMatch>");
  lines.push("</IfModule>");
  lines.push("");
  lines.push("# === Compression ===");
  lines.push("<IfModule mod_deflate.c>");
  lines.push("  AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml application/xml application/rss+xml");
  lines.push("</IfModule>");
  lines.push("");

  const out = join(process.cwd(), "public", ".htaccess");
  mkdirSync(join(process.cwd(), "public"), { recursive: true });
  writeFileSync(out, lines.join("\n"), "utf8");

  console.log(`✓ Wrote ${out}`);
  console.log(`  ${written} redirects + 3 affiliate wildcards`);
  if (skipped) console.log(`  skipped ${skipped} (duplicate or self-loop)`);
}

main().catch((err) => {
  console.error("✗ generate-htaccess failed:", err);
  process.exit(1);
});
